import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import {Saira_Condensed} from "next/font/google"

const Saira = Saira_Condensed({
  subsets: ['latin'],
  weight: ['100', '300', '700'],
  variable: '--font-Saira',
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={Saira.variable}
      >
        {children}
      </body>
    </html>
  );
}
