import type { Metadata } from "next";
import "./styles/globals.css";
import {Saira_Condensed} from "next/font/google"

const Saira = Saira_Condensed({
  subsets: ['latin'],
  weight: ['100', '300', '700'],
  variable: '--font-Saira',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={Saira.variable}
      >
        {children}
      </body>
    </html>
  );
}
